import esbuild from "esbuild";
import process from "process";
import { builtinModules as builtins } from "node:module";
import { readFileSync } from "fs";

const manifest = JSON.parse(readFileSync("./manifest.json", "utf8"));

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
	define: {
		"process.env.TELEMETRY_ENDPOINT": JSON.stringify(process.env.TELEMETRY_ENDPOINT || "https://telemetry.jinmu.me"),
		"process.env.TELEMETRY_API_KEY": JSON.stringify(process.env.TELEMETRY_API_KEY || "telemetry-dev-key"),
		"process.env.PLUGIN_VERSION": JSON.stringify(manifest.version),
	},
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}